name: Generate Snake

on:
  # Roda automaticamente todo dia à meia-noite
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      
      - name: Gerar a Cobrinha (Snake)
        uses: Platane/snk@v3
        with:
          # Usa o nome do dono do repositório automaticamente
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          # Token de segurança padrão do GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar no branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
